name: 01 - Intro au Action

on:
  workflow_dispatch:

jobs:
  restore_project:
    runs-on: ubuntu-latest
    steps:
      - name: View initial files
        run: ls -a -l
      - name: Get code of repo → Checkout !
        uses: actions/checkout@v6
      - name: View files after checkout
        run: ls -a -l